{
 "title": "黑盒拨测",
 "description": "支持Grafana 8，基于blackbox_exporter 0.19.0设计；采用图表+曲线图方式展示TCP，ICMP，HTTPS的服务状态，各阶段请求延时，HTTPS证书信息等；优化展示效果，支持监控目标的分组、分类级联展示，多服务同时对比展示。",
 "tags": [
  "StarsL.cn",
  "blacbox_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "label": "类型",
    "query": {
     "query": "label_values(probe_success,module)"
    }
   },
   {
    "name": "company",
    "label": "公司",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\"},company)"
    }
   },
   {
    "name": "project",
    "label": "项目",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\"},project)"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\"},env)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\"},instance)"
    }
   },
   {
    "name": "count",
    "query": {
     "query": "query_result(count(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}))"
    }
   },
   { "name": "sname", "label": "URL筛选(正则)" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "状态明细，资源数量：$count",
   "type": "table",
   "description": "注意：对于有重定向的URL，如果重定向后的域名与检查的域名不同，则检查的证书信息为重定向后的域名证书信息。如果需要检查源域名信息，请在blackbox中增加禁止重定向参数。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-time())/3600/24"
    },
    {
     "expr": "probe_http_version{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "probe_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"} - 0"
    },
    {
     "expr": "sum_over_time(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}[60m])/count_over_time(probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}[60m])"
    },
    {
     "expr": "probe_tls_version_info{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-0"
    },
    {
     "expr": "probe_http_redirects{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}-0"
    }
   ]
  },
  { "title": "明细 $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "连通性占比",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_success{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"})"
    }
   ]
  },
  {
   "title": "检测总耗时 $env $name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS检测类 阶段耗时 $env $name",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}} {{phase}}"
    }
   ]
  },
  {
   "title": "HTTP 状态占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"})"
    }
   ]
  },
  {
   "title": "网站HTTP状态检查 $env $name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{module=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\",instance=~\"$instance\",instance=~\".*$sname.*\"}",
     "legendFormat": "{{env}}_{{name}} "
    }
   ]
  }
 ]
}