services:
  jenkins:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/jenkins:2.555.2-jdk21
    container_name: jenkins
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
    - jenkins-net
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
networks:
  jenkins-net:
    driver: bridge
    name: jenkins-net
volumes:
  jenkins-data:
    name: jenkins-data